GET https://localhost:7188/api/igreja/listar HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwiZW1haWwiOiJmYWJiaW9saW1tYWRhc2lsdmFAZ21haWwuY29tIiwicm9sZSI6IkFkbWluaXN0cmFkb3IiLCJuYmYiOjE3ODA3Mzk3NzksImV4cCI6MTc4MDk1NTc3OSwiaWF0IjoxNzgwNzM5Nzc5LCJpc3MiOiJCb2xldGltSUFTRF9BUEkiLCJhdWQiOiJCb2xldGltSUFTRF9WdWVBcHAifQ.hEVljONmYhHK453eGnCtd1lraUlc3qFGtb-wmG9sX80

